version: '3'

services:
  blog_prod:
    build:
      context: .
      dockerfile: prod.dockerfile
    restart: on-failure
    container_name: blog_prod
    environment:
      VIRTUAL_HOST: 'blog.rafaelgss.com.br'
      # DATABASE_URL: 'mysql://root:alB85Nicr^8@64.225.123.69/blog_production'
      # SECRET_KEY_BASE: 'jm6oAbv0yegPXrLqRKP3fvb+3kNoqfZupQXxE84Wwg8qWs5V+Jq1SndAFIN03NLm'
    env_file:
      - ./.env
    ports:
      - '4000:4000'

  blog_dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IMAGE_ENVIRONMENT: dev
    restart: on-failure
    container_name: blog_dev
    # command: 'mix deps.get && mix phx.server'
    environment:
      DATABASE_URL: mysql://root:root@blog_mysql/blog_development
    volumes:
      - '.:/app'
    ports:
      - '4000:4000'
    depends_on:
      - blog_mysql
    networks:
      - netw

  blog_mysql:
    image: mysql:8
    container_name: blog_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '9005:3306'
    networks:
      - netw

networks:
  netw:
    external:
      name: netw
