version: '3'

services:
  blog_dev:
    build:
      context: .
      dockerfile: Dockerfile
    # command: bash -c "mix deps.get && mix phx.server"
    restart: on-failure
    container_name: blog_dev
    environment:
      DATABASE_URL: mysql://root:root@blog_mysql/blog_development
    volumes:
      - '.:/app'
    ports:
      - '4000:4000'
    depends_on:
      - blog_mysql
    networks:
      - netw

  blog_mysql:
    image: mysql:8
    container_name: blog_mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '9005:3306'
    networks:
      - netw

networks:
  netw:
    external:
      name: netw
